server.port=8083
spring.application.name=staff-service

# DataSource
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=staff_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Feign URLs
customer.service.url=http://localhost:8081
driver.service.url=http://localhost:8082
auth.service.url=http://localhost:8080

# JWT Config
jwt.secret=your_super_secret_key_which_needs_to_be_long_enough
jwt.expiration=86400000
