apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- auth-service
- customer-service
- staff-service
- driver-service
- payment-service
- backend
- frontend
- frontend-staff
- database
- redis
- kong
