apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ralsei-be
  labels:
    app.kubernetes.io/name: ralsei-be
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ralsei-be
      app.kubernetes.io/component: backend
