apiVersion: v1
kind: Service
metadata:
  name: ralsei-be
  labels:
    app.kubernetes.io/name: ralsei-be
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ralsei-be
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
