apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: ralsei/driver-service:latest
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: driver-service-config
