stages:
  - trigger

frontend:
  stage: trigger
  trigger:
    include: frontend-react/.gitlab-ci.yml

frontend-staff:
  stage: trigger
  trigger:
    include: frontend-react-staff/.gitlab-ci.yml

backend:
  stage: trigger
  trigger:
    include: backend-springboot/.gitlab-ci.yml