apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
      - name: staff-service
        image: ralsei/staff-service:latest
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: staff-service-config
