spring.application.name=application

# Cấu hình kết nối SQL Server (hoặc MySQL/PostgreSQL tùy database anh dùng)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VeXeDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=loliconhihi
spring.datasource.password=<cc>
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect