stages:
  - build
  - deploy

build-be:
  stage: build
  script:
    - docker build -t nhaxetuanmv-be:latest .

deploy-be:
  stage: deploy
  script:
    - docker stop nhaxetuanmv-be 2>/dev/null || true
    - docker rm nhaxetuanmv-be 2>/dev/null || true
    - docker run -d --name nhaxetuanmv-be -p 8082:8080 nhaxetuanmv-be:latest