server.port = 9090

spring.application.name=application

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VeXeDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
#spring.datasource.password=01102006Duc.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Số lượng kết nối tối đa được giữ sẵn trong bộ nhớ (Mặc định là 10, tùy tải có thể nâng lên 20-50)
spring.datasource.hikari.maximum-pool-size=20
# Thời gian tối đa (tính bằng mili-giây) mà 1 request phải xếp hàng chờ để mượn được 1 kết nối trống từ pool
# Quá thời gian này hệ thống sẽ ném lỗi Timeout (30000ms = 30 giây)
spring.datasource.hikari.connection-timeout=30000
# Thời gian tối đa một kết nối được phép "rảnh rỗi" (idle) trong pool trước khi bị giải phóng giải nhiệt cho DB
spring.datasource.hikari.idle-timeout=600000
# Tuổi thọ tối đa của một kết nối trong pool (Bắt buộc phải nhỏ hơn thời gian tự ngắt kết nối của SQL Server)
spring.datasource.hikari.max-lifetime=1800000
#xử lý con spring session jdbc để lưu session dưới DB thay vì trên RAM:
spring.session.jdbc.initialize-schema=always


# SSL Configuration
server.ssl.key-store=classpath:keystore.p12
# đụ mạ mi commit trước mi tế tổ cái ssl của https lên cho cả github ròm à thằng kiaaaaa
# bố m fix dùm r đó. mai cảm ơn t sau
server.ssl.key-store-password=${SSL_STORE_PASSWORD:fNPc~g_(@0qj}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

# Firebase Admin SDK - path to service account key file (classpath or absolute path)
firebase.service-account-key=firebase-service-account.json


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE