stages:
  - build
  - deploy

build-fe-customer:
  stage: build
  script:
    - docker build -t nhaxetuanmv-fe:latest .

deploy-fe-customer:
  stage: deploy
  script:
    - docker stop nhaxetuanmv-fe 2>/dev/null || true
    - docker rm nhaxetuanmv-fe 2>/dev/null || true
    - docker run -d --name nhaxetuanmv-fe -p 8080:80 nhaxetuanmv-fe:latest