apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: staff.nhaxetuanmv.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-staff
            port:
              number: 80
  - host: nhaxetuanmv.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
