stages:
  - build
  - deploy

build-fe-staff:
  stage: build
  script:
    - docker build -t nhaxetuanmv-fe-staff:latest ./frontend-react-staff

deploy-fe-staff:
  stage: deploy
  script:
    - docker stop nhaxetuanmv-fe-staff 2>/dev/null || true
    - docker rm nhaxetuanmv-fe-staff 2>/dev/null || true
    - docker run -d --name nhaxetuanmv-fe-staff -p 8081:80 nhaxetuanmv-fe-staff:latest